### PR TITLE
Fix TransformCoordinate

### PR DESCRIPTION
**Pull request by der-antikeks**
Correction for a minor error. Should only affect perspective matrices.

### CODE REVIEW

**Comment by shurcooL** [comment]
Thanks for the fix @der-antikeks.

You'll want to do one more step in order to have the change apply to the `mgl64` package as well, and that is run:

```bash
go generate github.com/go-gl/mathgl/mgl32
```

You can read https://github.com/go-gl/mathgl#contributing for more details.

**Comment by der-antikeks** [comment]
I have done this a while ago. Still missing something for a merge?

**Comment by hydroflame** [comment]
reviewing right now

**Comment by hydroflame** [comment]
I'm pretty sure that's right too, but could you link to some trustable source that explain the division by W ?

**Comment by shurcooL** [comment]
As I understand, the division by W was there before, it's just that its result was thrown away instead of being assigned to `t`. This PR fixes that.

LGTM.

> I have done this a while ago. Still missing something for a merge?

Sorry, I missed it back then.

**Comment by shurcooL** [comment]
The documentation for that func (https://godoc.org/github.com/go-gl/mathgl/mgl32#TransformCoordinate) itself says:

> This is effectively equivalent to the GLSL code
>
> ```
> vec4 r = (m * vec4(v,1.));
> r = r/r.w;
> vec3 newV = r.xyz;
> ```

**Comment by hydroflame** [comment]
Yeah, but I can write anything in comments that doesn't mean it's true. I know that the statement before was effectively a noop. It would've been nice to link to like a trusted source that states how this works.

**Comment by shurcooL** [comment]
> It would've been nice to link to like a trusted source that states how this works.

Sure. It can still be done.

Equally, if there's a trusted source saying this shouldn't be done, then we can revert this.

**Comment by der-antikeks** [comment]
In brief: To make perspecitive distortion work. Or to quote [wikipedia](https://en.wikipedia.org/wiki/Transformation_matrix#Perspective_projection): 

> After carrying out the matrix multiplication, the homogeneous component w will, in general, not be equal to 1. Therefore, to map back into the real plane we must perform the homogeneous divide or perspective divide by dividing each component by w.

A slightly longer but much more understandable explanation can be found [here](http://www.tomdalling.com/blog/modern-opengl/explaining-homogenous-coordinates-and-projective-geometry/).

**Pull request merged**
