### PR TITLE
#48 fixed. VecN with new funcs Set, Vec2, Vec3, Vec4.

### PR DESCRIPTION
**Pull request by shogg**
#48 fix + test for mgl32/64.

### CODE REVIEW

**Comment by hydroflame** [comment]
Uh, can you change the templates and not the source files ?

**Comment by shogg** [comment]
There isn't a template for VecN or is there?

**Comment by hydroflame** [comment]
IIRC everything except utils and _test are template generate.

**Comment by shogg** [comment]
As I said before there is no template. Could somebody please check it?

**Comment by Jragonmiris** [comment]
LGTM

**Comment by shurcooL** [comment]
I'm not sure why Travis did not run on this PR (maybe a configuration issue?).

It's [failing on master](https://travis-ci.org/go-gl/mathgl/builds/84609251) now because of a vet issue:

```
$ go tool vet ./
mgl32/matstack/transformstack_test.go:124: ExampleReseed refers to unknown identifier: Reseed
mgl64/matstack/transformstack_test.go:127: ExampleReseed refers to unknown identifier: Reseed

The command "go tool vet ./" exited with 1.
```

**Comment by Jragonmiris** [comment]
Good eye. Not sure what's up with Travis. It used to run on PRs. I reverted this until this is fixed.

**Comment by shurcooL** [comment]
That failure is unrelated to this PR, so reverting it did not help.

**Comment by shurcooL** [comment]
Updating to Go 1.5 has fixed the problem, the Travis build succeeds now.

**Comment by shurcooL** [comment]
I've reapplied the change in 667e7964455c5d0db23927d59cfd72852686e419 (since it was previously reviewed and accepted in this PR, and the build failure is resolved now).

**Pull request merged**
